// GENERATED FILE — do not edit by hand.
//
// Every default package line, translated once and shipped with the app, so a
// Marathi quotation needs no network at all. Regenerate after changing
// data/quotationSpecs.ts:
//
//   node scripts/buildMarathiGlossary.mjs
//
// Corrections to wording belong in lib/marathiQuotation.ts (TERMS or FIXES);
// they are applied on top of this file, so a fix reaches these lines too.

export const GLOSSARY: Record<string, string> = {
  "16\" x 16\"  —  Rs. 35 / sq.ft": "१६\" x १६\" - रु. 35 / चौ.फू",
  "2' x 1'  —  Rs. 30 / sq.ft": "2' x 1' - रु. 30 / चौ.फू",
  "2' x 2'  —  Rs. 35 / sq.ft": "2' x 2' - रु. 35 / चौ.फू",
  "2000 litre water tank (Plasto)": "2000 लिटर पाण्याची टाकी (प्लास्टो)",
  "4' x 2'  —  Rs. 50 / sq.ft": "४' x २' - रु. 50 / चौ.फू",
  "A store room on site for material and labour.": "साहित्य आणि कामगारांसाठी साइटवर एक स्टोअर रूम.",
  "Aggregate — crush sand.": "खडी — चुरा वाळू.",
  "All work as per the architect's drawing.": "आर्किटेक्टच्या रेखांकनानुसार सर्व काम.",
  "An RCC overhead water tank, if required, is charged extra.": "आरसीसी ओव्हरहेड पाण्याची टाकी, आवश्यक असल्यास, अतिरिक्त शुल्क आकारले जाते.",
  "Any dispute with a neighbour or the corporation is to be resolved by the client.": "शेजारी किंवा कॉर्पोरेशनशी कोणताही वाद ग्राहकाने सोडवला पाहिजे.",
  "Any work not listed in this quotation is charged extra.": "या कोटेशनमध्ये सूचीबद्ध नसलेल्या कोणत्याही कामासाठी अतिरिक्त शुल्क आकारले जाते.",
  "As per the architect's drawing, with plate shuttering for slabs.": "आर्किटेक्टच्या रेखांकनानुसार, स्लॅबसाठी प्लेट शटरिंगसह.",
  "Balcony  —  Rs. 550 / rft": "बाल्कनी - रु. 550 / rft",
  "Balcony  —  Rs. 800 / rft": "बाल्कनी - रु. 800 / rft",
  "Bathroom and balcony flooring — 600 x 600mm anti-skid tile.": "स्नानगृह आणि बाल्कनी फ्लोअरिंग — ६०० x ६०० मिमी अँटी-स्किड टाइल.",
  "Bathroom and toilet ventilators with louvered glass and mosquito net.": "लाउव्हर ग्लास आणि मच्छरदाणीसह बाथरूम आणि टॉयलेट व्हेंटिलेटर.",
  "Bathroom dado — 1200 x 600mm tile.": "बाथरूम डॅडो - 1200 x 600 मिमी टाइल.",
  "Bathroom dado — 300 x 600mm tile.": "बाथरूम डॅडो - 300 x 600 मिमी टाइल.",
  "Bathroom doors in FRP, with tadi patti, hinges and fittings.": "FRP मध्ये बाथरूमचे दरवाजे, ताडी पट्टी, बिजागर आणि फिटिंगसह.",
  "Bathroom flooring — 300 x 300mm anti-skid tile.": "बाथरूम फ्लोअरिंग — ३०० x ३०० मिमी अँटी-स्किड टाइल.",
  "Bathroom — P-trap commode, flush tank, mixer set and wash basin.": "स्नानगृह - पी-ट्रॅप कमोड, फ्लश टँक, मिक्सर सेट आणि वॉश बेसिन.",
  "Bathroom — wall-hung commode, flush valve, diverter spout set and wash basin.": "बाथरूम — वॉल-हँग कमोड, फ्लश व्हॉल्व्ह, डायव्हर्टर स्पाउट सेट आणि वॉश बेसिन.",
  "Birla Super": "बिर्ला सुपर",
  "Birla Super 53 Grade": "बिर्ला सुपर 53 ग्रेड",
  "Brand - Nerolac/Asian": "ब्रँड - नेरोलॅक/आशियाई",
  "Brick work as per the architect's drawing, in red brick. All walls 6\".": "आर्किटेक्टच्या रेखांकनानुसार विटांचे काम, लाल विटांमध्ये. सर्व भिंती 6\"",
  "Brick work as per the architect's drawing, in red brick. Outer walls 9\", internal walls 6\".": "आर्किटेक्टच्या रेखांकनानुसार विटांचे काम, लाल विटांमध्ये. बाह्य भिंती 9\", अंतर्गत भिंती 6\".",
  "Brick work — outer walls 9\", internal walls 6\", in red brick or AAC block.": "विटांचे काम — बाह्य भिंती 9\", अंतर्गत भिंती 6\", लाल वीट किंवा AAC ब्लॉकमध्ये.",
  "Brick — red brick / AAC block.": "वीट — लाल वीट / AAC ब्लॉक.",
  "Brickbat waterproofing in all bathrooms.": "सर्व स्नानगृहांमध्ये ब्रिकबॅट वॉटरप्रूफिंग.",
  "Cement — as per the brands table.": "सिमेंट - ब्रँड टेबलनुसार.",
  "Cera or Varmora": "सेरा किंवा वरमोरा",
  "Chicken mesh and chemical": "चिकन जाळी आणि रासायनिक",
  "Chicken mesh and chemical for plaster.": "मलमसाठी चिकन जाळी आणि रसायन.",
  "Compound wall and gate are not included.": "कंपाउंड वॉल आणि गेट समाविष्ट नाहीत.",
  "Compound wall and gate.": "कंपाउंड वॉल आणि गेट.",
  "Concealed points in 25-18mm pipe, with switches and sockets.": "25-18 मिमी पाईपमध्ये लपविलेले बिंदू, स्विचेस आणि सॉकेट्ससह.",
  "Crush sand for other work": "इतर कामासाठी वाळूचा चुरा",
  "Curing of the project is in the client's scope, along with a store room on site for material and labour.": "मटेरियल आणि मजुरांसाठी साइटवर स्टोअर रूमसह प्रकल्पाचे क्युरिंग ग्राहकाच्या जबाबदारीत आहेत.",
  "Curing of the project is in the client's scope.": "प्रकल्पाचा क्युरिंग हा ग्राहकाच्या जबाबदारीत आहे.",
  "Diverter (Rs. 6,000)": "डायव्हर्टर (रु. 6,000)",
  "Door  —  Rs. 180 / sq.ft": "दार - रु. 180 / चौ.फू",
  "Door  —  Rs. 60 / sq.ft": "दार - रु. 60 / चौ.फू",
  "Door frames in Steel Gray granite. Any other granite is charged extra.": "स्टील ग्रे ग्रॅनाइट मध्ये दरवाजा फ्रेम. इतर कोणत्याही ग्रॅनाइटसाठी अतिरिक्त शुल्क आकारले जाते.",
  "Door frames in Z-black granite. Any other granite is charged extra.": "Z-ब्लॅक ग्रॅनाइटमधील दरवाजाच्या फ्रेम्स. इतर कोणत्याही ग्रॅनाइटसाठी अतिरिक्त शुल्क आकारले जाते.",
  "Dr. Fixit URP and LW+": "डॉ. फिक्सिट URP आणि LW+",
  "Electrical points as per the architect's drawing.": "आर्किटेक्टच्या रेखांकनानुसार इलेक्ट्रिकल पॉइंट्स.",
  "Electrical work starts after the MSEB meter and main connection, arranged by the client.": "MSEB मीटर आणि मुख्य कनेक्शन, ग्राहकाने व्यवस्था केल्यानंतर इलेक्ट्रिकल काम सुरू होते.",
  "Electrical work starts after the MSEB meter and main connection.": "एमएसईबी मीटर आणि मुख्य जोडणीनंतर इलेक्ट्रिकल काम सुरू होते.",
  "Electricity and water connections, borewell and electric meter.": "वीज आणि पाण्याची जोडणी, बोअरवेल आणि इलेक्ट्रिक मीटर.",
  "Electricity, water, borewell and electric meter are in the client's scope, along with water tankers and space to store water until the underground tank is ready.": "वीज, पाणी, बोअरवेल आणि इलेक्ट्रिक मीटर ग्राहकांच्या जबाबदारीत आहेत, पाण्याचे टँकर आणि भूमिगत टाकी तयार होईपर्यंत पाणी साठवण्यासाठी जागा.",
  "Exterior — 1 coat primer, 2 coats paint.": "बाह्य - 1 कोट प्राइमर, 2 कोट पेंट.",
  "Exterior — Nerolac Suraksha Plus": "बाह्य - नेरोलॅक सुरक्षा प्लस",
  "External facade work such as mouldings is not included; standard plaster is considered. Any external detailing is charged extra.": "बाह्य दर्शनी कार्य जसे की मोल्डिंग्ज समाविष्ट नाहीत; मानक प्लास्टर मानले जाते. कोणत्याही बाह्य तपशीलासाठी अतिरिक्त शुल्क आकारले जाते.",
  "External facade work such as mouldings; standard plaster is considered. Any external detailing is charged extra.": "बाह्य दर्शनी कार्य जसे की मोल्डिंग; मानक प्लास्टर मानले जाते. कोणत्याही बाह्य तपशीलासाठी अतिरिक्त शुल्क आकारले जाते.",
  "External plumbing, chambers, and connection to the septic tank or main line.": "बाह्य प्लंबिंग, चेंबर्स आणि सेप्टिक टाकी किंवा मुख्य लाईनशी कनेक्शन.",
  "External — double coat plaster, 12mm each: taar plaster, then dabba finish.": "बाह्य — डबल कोट प्लास्टर, प्रत्येकी 12 मिमी: तार प्लास्टर, नंतर डब्बा फिनिश.",
  "Five points per room: fan, light, AC, charging and one spare.": "प्रति खोली पाच पॉइंट्स: पंखा, लाईट, एसी, चार्जिंग आणि एक स्पेअर.",
  "Flooring — 1200 x 1200mm tile, within the rate considered.": "फ्लोअरिंग — 1200 x 1200 मिमी टाइल, विचारात घेतलेल्या दरामध्ये.",
  "Flooring — 600 x 600mm tile, within the rate considered.": "फ्लोअरिंग — 600 x 600 मिमी टाइल, विचारात घेतलेल्या दरामध्ये.",
  "Flush tank (Rs. 2,000)": "फ्लश टँक (रु. 2,000)",
  "Flush valve (Rs. 6,000)": "फ्लश व्हॉल्व्ह (रु. 6,000)",
  "GST 18% extra on the base amount.": "मूळ रकमेवर 18% अतिरिक्त GST.",
  "If excavation and back-filling are done by the client, the plinth rate is considered as 75% of the slab area.": "उत्खनन आणि बॅक-फिलिंग ग्राहकाकडून केले असल्यास, प्लिंथचा दर स्लॅब क्षेत्राच्या 75% मानला जातो.",
  "In bathrooms and balconies, where the area is small, some water may collect — this is normal.": "बाथरुम आणि बाल्कनीमध्ये, जेथे क्षेत्र लहान आहे, तेथे थोडे पाणी जमा होऊ शकते — हे सामान्य आहे.",
  "In case of natural disaster, pandemic or war, the project timeline extends accordingly.": "नैसर्गिक आपत्ती, महामारी किंवा युद्धाच्या बाबतीत, प्रकल्पाची कालमर्यादा त्यानुसार वाढविली जाते.",
  "Indian commode (Rs. 2,000)": "भारतीय कमोड (रु. 2,000)",
  "Interior — Nerolac Tractor Emulsion": "आतील - नेरोलॅक ट्रॅक्टर इमल्शन",
  "Interior — Oil Bound Distemper (OBD)": "आतील - ऑइल बाउंड डिस्टेंपर (OBD)",
  "Interior — emulsion: 1 coat primer, 2 coats putty, 2 coats paint.": "इंटीरियर — इमल्शन: 1 कोट प्राइमर, 2 कोट्स पुट्टी, 2 कोट्स पेंट.",
  "Interior — oil bound distemper: 1 coat primer, 2 coats putty, 2 coats paint.": "इंटीरियर — ऑइल बाउंड डिस्टेंपर: 1 कोट प्राइमर, 2 कोट्स पुटी, 2 कोट्स पेंट.",
  "Internal lines concealed, external lines clamped, in CPVC, UPVC and PVC pipes.": "CPVC, UPVC आणि PVC पाईप्समध्ये अंतर्गत रेषा लपवलेल्या, बाह्य रेषा क्लॅम्प केलेल्या.",
  "Internal walls — 12mm sanla-finish plaster. External walls — 12mm single-coat dabba finish, with plaster sand.": "अंतर्गत भिंती - 12 मिमी सनला-फिनिश प्लास्टर. बाह्य भिंती — 12 मिमी सिंगल-कोट डब्बा फिनिश, प्लास्टर वाळूसह.",
  "Internal walls — 12mm taar-finish plaster. External walls — double coat: 12mm taar plaster, then 12mm dabba finish, with plaster sand.": "अंतर्गत भिंती - 12 मिमी taar फिनिश प्लास्टर. बाह्य भिंती — दुहेरी कोट: 12 मिमी टार प्लास्टर, नंतर 12 मिमी डब्बा फिनिश, प्लास्टर वाळूसह.",
  "Internal — taar plaster throughout.": "अंतर्गत — टार प्लास्टर संपूर्ण.",
  "Inverter and its wiring are not included; charged extra as required.": "इन्व्हर्टर आणि त्याचे वायरिंग समाविष्ट नाही; आवश्यकतेनुसार अतिरिक्त शुल्क आकारले जाते.",
  "JK Super": "जेके सुपर",
  "JK Super 43 Grade": "जेके सुपर ४३ ग्रेड",
  "Kitchen  —  Rs. 180 / sq.ft": "किचन - रु. 180 / चौ.फू",
  "Kitchen  —  Rs. 300 / sq.ft": "किचन - रु. 300 / चौ.फू",
  "Kitchen platform in Z-black granite.": "झेड-ब्लॅक ग्रॅनाइटमध्ये किचन प्लॅटफॉर्म.",
  "Kitchen platform in quartz.": "क्वार्ट्जमध्ये किचन प्लॅटफॉर्म.",
  "Landscaping of the outer area beside the parking is not included.": "पार्किंगच्या बाजूला बाहेरील भागाचे लँडस्केपिंग समाविष्ट नाही.",
  "Landscaping of the outer area beside the parking.": "पार्किंगच्या बाजूला बाह्य भागाचे लँडस्केपिंग.",
  "Light and fan fittings are provided by the client.": "लाईट आणि फॅन फिटिंग ग्राहकाकडून प्रदान केले जातात.",
  "Light and fan fittings are provided by the client. Their positions to be given by the architect one week before the slab.": "लाईट आणि फॅन फिटिंग ग्राहकाकडून प्रदान केले जातात. त्यांची पदे आर्किटेक्टने स्लॅबच्या एक आठवडा आधी द्यावीत.",
  "M sand (plaster sand)": "एम वाळू (प्लास्टर वाळू)",
  "MS window grills in 10mm bar, typical Bombay design, or as selected on site.": "एमएस विंडो ग्रिल 10 मिमी बारमध्ये, ठराविक बॉम्बे डिझाइन किंवा साइटवर निवडल्याप्रमाणे.",
  "Main and bedroom doors — flush, laminated both sides, with locks, hinges and fittings.": "मुख्य आणि बेडरूमचे दरवाजे - फ्लश, दोन्ही बाजू लॅमिनेटेड, कुलूप, बिजागर आणि फिटिंगसह.",
  "Manual concreting is considered. If RMC is required, the extra cost is added.": "मॅन्युअल काँक्रिटिंग मानले जाते. RMC आवश्यक असल्यास, अतिरिक्त खर्च जोडला जातो.",
  "Material selected above or below the stated rate is billed at the difference, including labour.": "नमूद केलेल्या दरापेक्षा वर किंवा खाली निवडलेल्या साहित्याला मजुरासह फरकाने बिल दिले जाते.",
  "Minor cracks may appear in walls due to heat of hydration — this is normal and causes no harm to the structure.": "हायड्रेशनच्या उष्णतेमुळे भिंतींमध्ये किरकोळ क्रॅक दिसू शकतात - हे सामान्य आहे आणि संरचनेला कोणतेही नुकसान होत नाही.",
  "Mixer (Rs. 4,000)": "मिक्सर (रु. 4,000)",
  "P-trap / S-trap commode (Rs. 4,000)": "पी-ट्रॅप / एस-ट्रॅप कमोड (रु. 4,000)",
  "POP (Plaster of Paris) for all internal walls, excluding bathrooms and ceilings.": "बाथरूम आणि छत वगळता सर्व अंतर्गत भिंतींसाठी POP (प्लास्टर ऑफ पॅरिस).",
  "Parking tile — 16\" x 16\".": "पार्किंग टाइल — १६\" x १६\".",
  "Per floor — 2.5 sq mm main; 1 sq mm light points; 1.5 sq mm power points.": "प्रति मजला - 2.5 चौरस मिमी मुख्य; 1 चौरस मिमी प्रकाश बिंदू; 1.5 चौरस मिमी पॉवर पॉइंट.",
  "Pipe — Diamond or Polycab": "पाईप - डायमंड किंवा पॉलीकॅब",
  "Plaster — M sand (plaster sand).": "प्लास्टर - एम वाळू (प्लास्टर वाळू).",
  "Plasto": "प्लास्टो",
  "Prince": "राजकुमार",
  "Prince / Paras": "राजकुमार / पारस",
  "RCC and brick work — Rs. 870 / sq.ft + taxes.": "आरसीसी आणि विटांचे काम - रु. 870 / चौ.फूट + कर.",
  "RCC overhead water tank, if required, is charged extra.": "आरसीसी ओव्हरहेड पाण्याची टाकी, आवश्यक असल्यास, अतिरिक्त शुल्क आकारले जाते.",
  "RCC tank — Rs. 25 / litre.": "आरसीसी टाकी - रु. 25 / लिटर.",
  "RCC work as per the structural drawings.": "स्ट्रक्चरल रेखांकनानुसार आरसीसी कार्य.",
  "Raft — Rs. 600 / sq.ft + taxes.": "राफ्ट - रु. 600 / चौ.फूट + कर.",
  "Rates for RCC and brick work with plaster, on built-up area, as per the measurement basis and scope below:": "प्लास्टरसह आरसीसी आणि विटांच्या कामासाठी, बिल्ट-अप क्षेत्रावर, मोजमापाच्या आधारावर आणि खाली दिलेल्या व्याप्तीनुसार दर:",
  "Red brick / AAC block": "लाल वीट / AAC ब्लॉक",
  "Retaining wall — Rs. 550 / sq.ft + taxes.": "रिटेनिंग वॉल - रु. 550 / चौ.फूट + कर.",
  "Rs. 14 / piece": "रु. 14 / तुकडा",
  "Rs. 150 / sq.ft": "रु. 150 / चौ.फू",
  "Sadab Gypsum": "सदब जिप्सम",
  "Shuttering rate varies with height: up to 3m — 1x; 3m to 3.5m — 1.25x; 3.5m to 4.5m — 1.5x; up to 6m — 2x.": "शटरिंग रेट उंचीनुसार बदलतो: 3m पर्यंत - 1x; 3m ते 3.5m - 1.25x; 3.5 मी ते 4.5 मी - 1.5x; 6m पर्यंत - 2x.",
  "Sliding windows — 3-track, 18x40mm section, white powder coated, with mosquito net.": "सरकत्या खिडक्या — 3-ट्रॅक, 18x40 मिमी विभाग, पांढरा पावडर लेपित, मच्छरदाणीसह.",
  "Staircase  —  Rs. 550 / rft": "जिना - रु. 550 / rft",
  "Staircase treads and risers in Steel Gray granite.": "स्टील ग्रे ग्रॅनाइटमध्ये पायऱ्या पायऱ्या आणि राइसर.",
  "Staircase treads and risers in Z-black granite.": "Z-ब्लॅक ग्रॅनाइटमध्ये पायऱ्यांची पायरी आणि राइसर.",
  "Staircase — SS railing in 2\" round, 1.5\" and 0.75\" pipe. Balcony — 10mm glass railing.": "जिना - SS रेलिंग 2\" गोल, 1.5\" आणि 0.75\" पाईपमध्ये. बाल्कनी - 10 मिमी काचेची रेलिंग.",
  "Steel — Fe 500 / 550.": "स्टील — Fe 500 / 550.",
  "Switch & Socket — Anchor Roma Penta": "स्विच आणि सॉकेट - अँकर रोमा पेंटा",
  "Terrace waterproofing in brickbat.": "ब्रिकबॅटमध्ये टेरेस वॉटरप्रूफिंग.",
  "Terrace waterproofing in ghotai finish.": "घोटाई फिनिशमध्ये टेरेस वॉटरप्रूफिंग.",
  "This quotation is valid for 15 days.": "हे कोटेशन 15 दिवसांसाठी वैध आहे.",
  "Tiles have a minor natural bend, so a slight difference in level may occur — this is normal.": "टाइलमध्ये किरकोळ नैसर्गिक वाकलेला असतो, त्यामुळे पातळीत थोडा फरक होऊ शकतो — हे सामान्य आहे.",
  "Uma / Kalika / equivalent (Fe 500 / 550)": "उमा / कालिका / समतुल्य (फे 500 / 550)",
  "Uma, Kalika or equivalent": "उमा, कालिका किंवा समतुल्य",
  "Wall hanging commode (Rs. 8,000)": "वॉल हँगिंग कमोड (रु. 8,000)",
  "Wash basin (Rs. 2,000)": "वॉश बेसिन (रु. 2,000)",
  "Wash basin (Rs. 2,500)": "वॉश बेसिन (रु. 2,500)",
  "Water tankers, if required, and space to store water until the underground tank is ready.": "पाण्याचे टँकर, आवश्यक असल्यास, आणि भूमिगत टाकी तयार होईपर्यंत पाणी साठवण्यासाठी जागा.",
  "Where a drainage line is available, all lines connect to it; no septic tank is constructed.": "जिथे ड्रेनेज लाईन उपलब्ध आहे तिथे सर्व लाईन त्याला जोडतात; सेप्टिक टाकी बांधलेली नाही.",
  "Window frames in single-piece Steel Gray granite, chamfer polished.": "खिडकीच्या फ्रेम सिंगल-पीस स्टील ग्रे ग्रॅनाइट, चेम्फर पॉलिशमध्ये.",
  "Window frames in single-piece pearl black granite, chamfer polished.": "सिंगल-पीस पर्ल ब्लॅक ग्रॅनाइटमधील खिडकीच्या फ्रेम्स, चेम्फर पॉलिश.",
  "Windows  —  Rs. 60 / sq.ft": "विंडोज - रु. 60 / चौ.फू",
  "Wire — Polycab": "वायर - पॉलीकॅब",
};
